services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: uni_backend:latest
    container_name: uni_backend
    restart: always
    environment:
      - DB=host=dpg-d06btjjuibrs73ee7r3g-a user=root password=KLbOmqsrOKgkxneVf5jAS0mWYuHKQbl1 dbname=chatbot_k3qg port=5432 sslmode=disable
      - PORT=${PORT:-8080} 
      - FRONTEND_URL=http://frontend:3000
    ports:
      - "8080:8080"
    networks:
      - uni_network
    dns:
      - 8.8.8.8
      - 1.1.1.1

networks:
  uni_network:
    driver: bridge