basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample server.
  title: UniGlobal
  version: "1.0"
paths: {}
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
